[package]
name = "teama-2024-25-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# These fields configure default behavior for uploads with `cargo v5`.
[package.metadata.v5]
slot = 1
icon = "cool-x"
compress = true

[dependencies]
log = "0.4.22"
pid = "4.0.0"
vexide = { git = "https://github.com/vexide/vexide.git", rev = "1f55deca079e25c7030db9429dee4afde1e8c80c" }
